eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
        exclude:
          - beans
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: ALWAYS
